name: dictionary
description: app dictionary
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  flutter_triple: ^1.2.7+4
  dartz: ^0.10.1
  dio: ^5.4.3+1
  dio_smart_retry: ^6.0.0
  pretty_dio_logger: ^1.2.0-beta-1
  shared_preferences: ^2.2.1
  intl: ^0.19.0
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.2.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/ca/lets-encrypt-r3.pem